apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: ${{ values.name }}
  janus-idp.io/tekton: ${{ values.name }}
  backstage.io/kubernetes-id: ${{ values.name }}
  backstage.io/kubernetes-namespace: ${{ values.namespace }}
  app.kubernetes.io/part-of: ${{ values.name }}
resources:
  - initialize-namespace/
  {%- if not values.llamaStackServerOnly %}
  - deployment.yaml
  - model-config.yaml
  {%- else %}
  - llama-stack-deployment.yaml
  - pvc.yaml
  {%- endif %}
  - service.yaml
  - route.yaml
  {%- if values.rhoaiSelected %}
  - rhoai/
  {%- endif %}

{%- if values.llamaStackServerOnly %}
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    files:
      - config.yaml=llama-stack-run.yaml
{%- endif %}