FROM registry.access.redhat.com/ubi9/python-311:1-77.1726664316
WORKDIR /chat
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /chat/requirements.txt
COPY llama_stack.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "llama_stack_chatbot.py" ]
